# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BrdrQ
                                 A QGIS plugin
 brdrQ, a QGIS-plugin for aligning thematic borders to reference borders.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-11
        copyright            : (C) 2024 by Karel Dieussaert / Onroerend Erfgoed
        email                : karel.dieussaert@vlaanderen.be
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = "Karel Dieussaert / Onroerend Erfgoed"
__date__ = "2024-10-11"
__copyright__ = "(C) 2024 by Karel Dieussaert / Onroerend Erfgoed"

from .qt_compat import dialog_exec, qmessagebox_critical_icon, qmessagebox_ok_button


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BrdrQ class from file BrdrQ.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .brdrq_module_importer import import_modules

    try:
        if not python_version_compatibility(iface):
            print("failed python version check")
            return None
        if not qgis_version_compatibility(iface):
            print("failed qgis version check")
            return None

        import_modules()
        print("modules succesfully loaded")
        from .brdrq_plugin import BrdrQPlugin

        return BrdrQPlugin(iface)
    except Exception as e:
        show_error_dialog(e)
        return None
        # raise RuntimeError("Error initializing brdrQ-plugin") #better to raise Error or to return None?


def qgis_version_compatibility(iface):
    from qgis.PyQt.QtWidgets import QMessageBox
    from qgis.core import Qgis

    # 1. Define requirements
    min_qgis = (3, 36, 0)

    # 2. Get current QGIS version
    q_ver_str = Qgis.QGIS_VERSION.split("-")[0].split(".")
    current_qgis = tuple(map(int, q_ver_str))

    req_str = ".".join(map(str, min_qgis))
    cur_str = ".".join(map(str, current_qgis))
    print(f" QGIS required{req_str} & current{cur_str}")

    # 3. Perform check
    if current_qgis < min_qgis:
        print("failed qgis version check")
        # We use iface.mainWindow() to ensure the dialog has a parent
        QMessageBox.critical(
            iface.mainWindow(),
            "brdrQ-Plugin Load Error",
            f"This plugin requires QGIS {req_str} or higher. You are running {cur_str}.",
        )
        return False  # QGIS will handle this gracefully as a load failure
    return True


def python_version_compatibility(iface):
    import sys
    from qgis.PyQt.QtWidgets import QMessageBox

    # 1. Define minimum Python version (e.g., 3.11)
    # Using a tuple makes comparison easy: (3, 11, 0) > (3, 9, 5)
    required_python = (3, 11, 0)
    current_python = sys.version_info[:3]

    req_str = ".".join(map(str, required_python))
    cur_str = ".".join(map(str, current_python))
    print(f"Python required {req_str} & current {cur_str}")

    # 2. Perform the check
    if current_python < required_python:
        print("failed python check")
        req_str = ".".join(map(str, required_python))
        cur_str = ".".join(map(str, current_python))

        msg = (
            f"<h3>Incompatible Python Version</h3>"
            f"brdrQ-plugin requires <b>Python {req_str}</b> or higher.<br>"
            f"You are currently running <b>Python {cur_str}</b>.<br><br>"
            f"Please upgrade QGIS to a more recent version."
        )

        QMessageBox.critical(iface.mainWindow(), "Dependency Error", msg)
        return False  # Tells QGIS that the plugin failed to load
    return True


def show_error_dialog(e):
    from qgis.PyQt.QtWidgets import QMessageBox

    msg = QMessageBox()
    msg.setIcon(qmessagebox_critical_icon())
    msg.setWindowTitle("brdrQ could not start")
    msg.setText("<b>brdrQ could not be loaded in this QGIS session.</b>")
    msg.setInformativeText(
        "This usually happens when QGIS is still using an old Python library "
        "or when a dependency was just installed or updated.<br><br>"
        "<b>What you can do:</b><br>"
        "1. Close QGIS completely.<br>"
        "2. Open QGIS again and enable brdrQ.<br>"
        "3. If this message appears again, update or reinstall brdrQ and check "
        "that your QGIS version is supported.<br><br>"
        "Your QGIS project and data were not changed by this startup error.<br><br>"
        "If the problem persists, please report it at "
        "<a href='https://github.com/OnroerendErfgoed/brdrQ/issues'>"
        "https://github.com/OnroerendErfgoed/brdrQ/issues</a>."
    )
    msg.setDetailedText(f"{type(e).__name__}: {e}")
    msg.setStandardButtons(qmessagebox_ok_button())
    dialog_exec(msg)
